services:
  mysql:
    image: mysql:8.0
    container_name: mysql_albaranes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: radio_root_2025!
      MYSQL_DATABASE: radio
      MYSQL_USER: radio
      MYSQL_PASSWORD: Rtx12345!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_albaranes:/var/lib/mysql
    networks:
      - albaranes_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_albaranes
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: radio
      PMA_PASSWORD: Rtx12345!
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - "8090:80"
    networks:
      - albaranes_network

networks:
  albaranes_network:
    driver: bridge

volumes:
  mysql_data_albaranes:
